version: "3"
services:
  web:
    build: .
    command: python manage.py runserver
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: arya
      MYSQL_USER: om
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 123qwe,./
    ports:
      - "3306:3306"
